2024-03-07 08:37:27,085 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Current SDK version is 0.16.4
2024-03-07 08:37:27,086 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Configure stats pid to 3776
2024-03-07 08:37:27,086 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Loading settings from /home2/surya_ravindra/.config/wandb/settings
2024-03-07 08:37:27,086 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Loading settings from /home2/surya_ravindra/CV_A2/wandb/settings
2024-03-07 08:37:27,087 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'CV_A1_Q2', 'entity': 'sriharib128', 'root_dir': '/home2/surya_ravindra/CV_A2', 'run_id': '7wvjejpc', 'sweep_param_path': '/home2/surya_ravindra/CV_A2/wandb/sweep-n67d31si/config-7wvjejpc.yaml', 'sweep_id': 'n67d31si'}
2024-03-07 08:37:27,087 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-07 08:37:27,087 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-07 08:37:27,087 INFO    MainThread:3776 [wandb_init.py:_log_setup():526] Logging user logs to /home2/surya_ravindra/CV_A2/wandb/run-20240307_083727-7wvjejpc/logs/debug.log
2024-03-07 08:37:27,087 INFO    MainThread:3776 [wandb_init.py:_log_setup():527] Logging internal logs to /home2/surya_ravindra/CV_A2/wandb/run-20240307_083727-7wvjejpc/logs/debug-internal.log
2024-03-07 08:37:27,087 INFO    MainThread:3776 [wandb_init.py:init():566] calling init triggers
2024-03-07 08:37:27,088 INFO    MainThread:3776 [wandb_init.py:init():573] wandb.init called with sweep_config: {'batch_size': 8, 'epochs': 5, 'learning_rate': 0.001, 'optimizer': 'sgd'}
config: {}
2024-03-07 08:37:27,088 INFO    MainThread:3776 [wandb_init.py:init():616] starting backend
2024-03-07 08:37:27,088 INFO    MainThread:3776 [wandb_init.py:init():620] setting up manager
2024-03-07 08:37:27,256 ERROR   MainThread:3776 [wandb_init.py:init():1204] error
Traceback (most recent call last):
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1176, in init
    run = wi.init()
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 621, in init
    manager._inform_init(
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/wandb_manager.py", line 200, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/service/service_sock.py", line 39, in _svc_inform_init
    self._sock_client.send(inform_init=inform_init)
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2024-03-07 08:38:27,637 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Current SDK version is 0.16.4
2024-03-07 08:38:27,638 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Configure stats pid to 3776
2024-03-07 08:38:27,638 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Loading settings from /home2/surya_ravindra/.config/wandb/settings
2024-03-07 08:38:27,638 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Loading settings from /home2/surya_ravindra/CV_A2/wandb/settings
2024-03-07 08:38:27,638 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'CV_A1_Q2', 'entity': 'sriharib128', 'root_dir': '/home2/surya_ravindra/CV_A2', 'run_id': '7wvjejpc', 'sweep_param_path': '/home2/surya_ravindra/CV_A2/wandb/sweep-n67d31si/config-7wvjejpc.yaml', 'sweep_id': 'n67d31si'}
2024-03-07 08:38:27,638 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-07 08:38:27,639 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-07 08:38:27,639 INFO    MainThread:3776 [wandb_init.py:_log_setup():526] Logging user logs to /home2/surya_ravindra/CV_A2/wandb/run-20240307_083827-7wvjejpc/logs/debug.log
2024-03-07 08:38:27,639 INFO    MainThread:3776 [wandb_init.py:_log_setup():527] Logging internal logs to /home2/surya_ravindra/CV_A2/wandb/run-20240307_083827-7wvjejpc/logs/debug-internal.log
2024-03-07 08:38:27,639 INFO    MainThread:3776 [wandb_init.py:init():566] calling init triggers
2024-03-07 08:38:27,639 INFO    MainThread:3776 [wandb_init.py:init():573] wandb.init called with sweep_config: {'batch_size': 8, 'epochs': 5, 'learning_rate': 0.001, 'optimizer': 'sgd'}
config: {}
2024-03-07 08:38:27,640 INFO    MainThread:3776 [wandb_init.py:init():616] starting backend
2024-03-07 08:38:27,640 INFO    MainThread:3776 [wandb_init.py:init():620] setting up manager
2024-03-07 08:38:27,807 ERROR   MainThread:3776 [wandb_init.py:init():1204] error
Traceback (most recent call last):
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1176, in init
    run = wi.init()
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 621, in init
    manager._inform_init(
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/wandb_manager.py", line 200, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/service/service_sock.py", line 39, in _svc_inform_init
    self._sock_client.send(inform_init=inform_init)
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2024-03-07 08:45:53,629 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Current SDK version is 0.16.4
2024-03-07 08:45:53,630 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Configure stats pid to 3776
2024-03-07 08:45:53,630 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Loading settings from /home2/surya_ravindra/.config/wandb/settings
2024-03-07 08:45:53,630 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Loading settings from /home2/surya_ravindra/CV_A2/wandb/settings
2024-03-07 08:45:53,630 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'CV_A1_Q2', 'entity': 'sriharib128', 'root_dir': '/home2/surya_ravindra/CV_A2', 'run_id': '7wvjejpc', 'sweep_param_path': '/home2/surya_ravindra/CV_A2/wandb/sweep-n67d31si/config-7wvjejpc.yaml', 'sweep_id': 'n67d31si'}
2024-03-07 08:45:53,630 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-07 08:45:53,630 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-07 08:45:53,631 INFO    MainThread:3776 [wandb_init.py:_log_setup():526] Logging user logs to /home2/surya_ravindra/CV_A2/wandb/run-20240307_084553-7wvjejpc/logs/debug.log
2024-03-07 08:45:53,631 INFO    MainThread:3776 [wandb_init.py:_log_setup():527] Logging internal logs to /home2/surya_ravindra/CV_A2/wandb/run-20240307_084553-7wvjejpc/logs/debug-internal.log
2024-03-07 08:45:53,631 INFO    MainThread:3776 [wandb_init.py:init():566] calling init triggers
2024-03-07 08:45:53,631 INFO    MainThread:3776 [wandb_init.py:init():573] wandb.init called with sweep_config: {'batch_size': 8, 'epochs': 5, 'learning_rate': 0.001, 'optimizer': 'sgd'}
config: {}
2024-03-07 08:45:53,631 INFO    MainThread:3776 [wandb_init.py:init():616] starting backend
2024-03-07 08:45:53,631 INFO    MainThread:3776 [wandb_init.py:init():620] setting up manager
2024-03-07 08:45:53,792 ERROR   MainThread:3776 [wandb_init.py:init():1204] error
Traceback (most recent call last):
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1176, in init
    run = wi.init()
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 621, in init
    manager._inform_init(
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/wandb_manager.py", line 200, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/service/service_sock.py", line 39, in _svc_inform_init
    self._sock_client.send(inform_init=inform_init)
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2024-03-07 08:51:11,196 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Current SDK version is 0.16.4
2024-03-07 08:51:11,198 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Configure stats pid to 3776
2024-03-07 08:51:11,198 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Loading settings from /home2/surya_ravindra/.config/wandb/settings
2024-03-07 08:51:11,199 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Loading settings from /home2/surya_ravindra/CV_A2/wandb/settings
2024-03-07 08:51:11,199 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'CV_A1_Q2', 'entity': 'sriharib128', 'root_dir': '/home2/surya_ravindra/CV_A2', 'run_id': '7wvjejpc', 'sweep_param_path': '/home2/surya_ravindra/CV_A2/wandb/sweep-n67d31si/config-7wvjejpc.yaml', 'sweep_id': 'n67d31si'}
2024-03-07 08:51:11,199 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-07 08:51:11,199 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-07 08:51:11,199 INFO    MainThread:3776 [wandb_init.py:_log_setup():526] Logging user logs to /home2/surya_ravindra/CV_A2/wandb/run-20240307_085111-7wvjejpc/logs/debug.log
2024-03-07 08:51:11,200 INFO    MainThread:3776 [wandb_init.py:_log_setup():527] Logging internal logs to /home2/surya_ravindra/CV_A2/wandb/run-20240307_085111-7wvjejpc/logs/debug-internal.log
2024-03-07 08:51:11,200 INFO    MainThread:3776 [wandb_init.py:init():566] calling init triggers
2024-03-07 08:51:11,200 INFO    MainThread:3776 [wandb_init.py:init():573] wandb.init called with sweep_config: {'batch_size': 8, 'epochs': 5, 'learning_rate': 0.001, 'optimizer': 'sgd'}
config: {}
2024-03-07 08:51:11,200 INFO    MainThread:3776 [wandb_init.py:init():616] starting backend
2024-03-07 08:51:11,201 INFO    MainThread:3776 [wandb_init.py:init():620] setting up manager
2024-03-07 08:51:11,387 ERROR   MainThread:3776 [wandb_init.py:init():1204] error
Traceback (most recent call last):
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1176, in init
    run = wi.init()
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 621, in init
    manager._inform_init(
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/wandb_manager.py", line 200, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/service/service_sock.py", line 39, in _svc_inform_init
    self._sock_client.send(inform_init=inform_init)
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
