2024-03-07 08:34:32,923 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Current SDK version is 0.16.4
2024-03-07 08:34:32,923 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Configure stats pid to 3776
2024-03-07 08:34:32,923 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Loading settings from /home2/surya_ravindra/.config/wandb/settings
2024-03-07 08:34:32,923 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Loading settings from /home2/surya_ravindra/CV_A2/wandb/settings
2024-03-07 08:34:32,923 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'CV_A1_Q2', 'entity': 'sriharib128', 'root_dir': '/home2/surya_ravindra/CV_A2', 'run_id': '7wvjejpc', 'sweep_param_path': '/home2/surya_ravindra/CV_A2/wandb/sweep-n67d31si/config-7wvjejpc.yaml', 'sweep_id': 'n67d31si'}
2024-03-07 08:34:32,923 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-07 08:34:32,923 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-07 08:34:32,924 INFO    MainThread:3776 [wandb_init.py:_log_setup():526] Logging user logs to /home2/surya_ravindra/CV_A2/wandb/run-20240307_083432-7wvjejpc/logs/debug.log
2024-03-07 08:34:32,924 INFO    MainThread:3776 [wandb_init.py:_log_setup():527] Logging internal logs to /home2/surya_ravindra/CV_A2/wandb/run-20240307_083432-7wvjejpc/logs/debug-internal.log
2024-03-07 08:34:32,924 INFO    MainThread:3776 [wandb_init.py:_jupyter_setup():472] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x14bbdcffb550>
2024-03-07 08:34:32,924 INFO    MainThread:3776 [wandb_init.py:init():566] calling init triggers
2024-03-07 08:34:32,924 INFO    MainThread:3776 [wandb_init.py:init():573] wandb.init called with sweep_config: {'batch_size': 8, 'epochs': 5, 'learning_rate': 0.001, 'optimizer': 'sgd'}
config: {}
2024-03-07 08:34:32,924 INFO    MainThread:3776 [wandb_init.py:init():591] re-initializing run, found existing run on stack: 7wvjejpc
2024-03-07 08:34:32,926 INFO    MainThread:3776 [wandb_run.py:_finish():1970] finishing run sriharib128/CV_A1_Q2/7wvjejpc
2024-03-07 08:34:32,926 INFO    MainThread:3776 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-03-07 08:34:32,927 INFO    MainThread:3776 [wandb_run.py:_restore():2193] restore
2024-03-07 08:34:32,927 INFO    MainThread:3776 [wandb_run.py:_restore():2199] restore done
2024-03-07 08:36:15,703 INFO    MainThread:3776 [wandb_init.py:init():616] starting backend
2024-03-07 08:36:15,703 INFO    MainThread:3776 [wandb_init.py:init():620] setting up manager
2024-03-07 08:36:15,719 INFO    MainThread:3776 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-03-07 08:36:15,720 INFO    MainThread:3776 [wandb_init.py:init():628] backend started and connected
2024-03-07 08:36:15,753 INFO    MainThread:3776 [wandb_run.py:_config_callback():1343] config_cb None None {'batch_size': 8, 'epochs': 5, 'learning_rate': 0.001, 'optimizer': 'sgd'}
2024-03-07 08:36:15,759 INFO    MainThread:3776 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-03-07 08:36:15,759 INFO    MainThread:3776 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-03-07 08:36:15,760 INFO    MainThread:3776 [wandb_init.py:init():720] updated telemetry
2024-03-07 08:36:15,866 INFO    MainThread:3776 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-03-07 08:36:17,138 WARNING MainThread:3776 [wandb_init.py:init():1198] interrupted
Traceback (most recent call last):
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1176, in init
    run = wi.init()
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 756, in init
    result = run_init_handle.wait(
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2024-03-07 08:36:26,724 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Current SDK version is 0.16.4
2024-03-07 08:36:26,724 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Configure stats pid to 3776
2024-03-07 08:36:26,724 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Loading settings from /home2/surya_ravindra/.config/wandb/settings
2024-03-07 08:36:26,724 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Loading settings from /home2/surya_ravindra/CV_A2/wandb/settings
2024-03-07 08:36:26,724 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'CV_A1_Q2', 'entity': 'sriharib128', 'root_dir': '/home2/surya_ravindra/CV_A2', 'run_id': '7wvjejpc', 'sweep_param_path': '/home2/surya_ravindra/CV_A2/wandb/sweep-n67d31si/config-7wvjejpc.yaml', 'sweep_id': 'n67d31si'}
2024-03-07 08:36:26,725 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-07 08:36:26,725 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-07 08:36:26,725 INFO    MainThread:3776 [wandb_init.py:_log_setup():526] Logging user logs to /home2/surya_ravindra/CV_A2/wandb/run-20240307_083626-7wvjejpc/logs/debug.log
2024-03-07 08:36:26,725 INFO    MainThread:3776 [wandb_init.py:_log_setup():527] Logging internal logs to /home2/surya_ravindra/CV_A2/wandb/run-20240307_083626-7wvjejpc/logs/debug-internal.log
2024-03-07 08:36:26,725 INFO    MainThread:3776 [wandb_init.py:init():566] calling init triggers
2024-03-07 08:36:26,725 INFO    MainThread:3776 [wandb_init.py:init():573] wandb.init called with sweep_config: {'batch_size': 8, 'epochs': 5, 'learning_rate': 0.001, 'optimizer': 'sgd'}
config: {}
2024-03-07 08:36:26,725 INFO    MainThread:3776 [wandb_init.py:init():616] starting backend
2024-03-07 08:36:26,726 INFO    MainThread:3776 [wandb_init.py:init():620] setting up manager
2024-03-07 08:36:26,737 INFO    MainThread:3776 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-03-07 08:36:26,738 INFO    MainThread:3776 [wandb_init.py:init():628] backend started and connected
2024-03-07 08:36:26,771 INFO    MainThread:3776 [wandb_run.py:_config_callback():1343] config_cb None None {'batch_size': 8, 'epochs': 5, 'learning_rate': 0.001, 'optimizer': 'sgd'}
2024-03-07 08:36:26,773 INFO    MainThread:3776 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-03-07 08:36:26,773 INFO    MainThread:3776 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-03-07 08:36:26,773 INFO    MainThread:3776 [wandb_init.py:init():720] updated telemetry
2024-03-07 08:36:26,874 INFO    MainThread:3776 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-03-07 08:36:57,226 WARNING MsgRouterThr:3776 [router.py:message_loop():77] message_loop has been closed
2024-03-07 08:36:57,226 WARNING MsgRouterThr:3776 [router.py:message_loop():77] message_loop has been closed
2024-03-07 08:36:57,226 WARNING MsgRouterThr:3776 [router.py:message_loop():77] message_loop has been closed
2024-03-07 08:37:02,082 ERROR   MainThread:3776 [wandb_init.py:init():1194] transport failed
Traceback (most recent call last):
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1176, in init
    run = wi.init()
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 756, in init
    result = run_init_handle.wait(
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/lib/mailbox.py", line 281, in wait
    raise MailboxError("transport failed")
wandb.sdk.lib.mailbox.MailboxError: transport failed
2024-03-07 08:37:19,805 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Current SDK version is 0.16.4
2024-03-07 08:37:19,805 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Configure stats pid to 3776
2024-03-07 08:37:19,805 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Loading settings from /home2/surya_ravindra/.config/wandb/settings
2024-03-07 08:37:19,805 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Loading settings from /home2/surya_ravindra/CV_A2/wandb/settings
2024-03-07 08:37:19,806 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'CV_A1_Q2', 'entity': 'sriharib128', 'root_dir': '/home2/surya_ravindra/CV_A2', 'run_id': '7wvjejpc', 'sweep_param_path': '/home2/surya_ravindra/CV_A2/wandb/sweep-n67d31si/config-7wvjejpc.yaml', 'sweep_id': 'n67d31si'}
2024-03-07 08:37:19,806 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-07 08:37:19,806 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-07 08:37:19,806 INFO    MainThread:3776 [wandb_init.py:_log_setup():526] Logging user logs to /home2/surya_ravindra/CV_A2/wandb/run-20240307_083719-7wvjejpc/logs/debug.log
2024-03-07 08:37:19,806 INFO    MainThread:3776 [wandb_init.py:_log_setup():527] Logging internal logs to /home2/surya_ravindra/CV_A2/wandb/run-20240307_083719-7wvjejpc/logs/debug-internal.log
2024-03-07 08:37:19,806 INFO    MainThread:3776 [wandb_init.py:init():566] calling init triggers
2024-03-07 08:37:19,806 INFO    MainThread:3776 [wandb_init.py:init():573] wandb.init called with sweep_config: {'batch_size': 8, 'epochs': 5, 'learning_rate': 0.001, 'optimizer': 'sgd'}
config: {}
2024-03-07 08:37:19,806 INFO    MainThread:3776 [wandb_init.py:init():616] starting backend
2024-03-07 08:37:19,806 INFO    MainThread:3776 [wandb_init.py:init():620] setting up manager
2024-03-07 08:37:20,033 ERROR   MainThread:3776 [wandb_init.py:init():1204] error
Traceback (most recent call last):
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1176, in init
    run = wi.init()
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 621, in init
    manager._inform_init(
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/wandb_manager.py", line 200, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/service/service_sock.py", line 39, in _svc_inform_init
    self._sock_client.send(inform_init=inform_init)
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2024-03-07 08:37:27,085 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Current SDK version is 0.16.4
2024-03-07 08:37:27,086 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Configure stats pid to 3776
2024-03-07 08:37:27,086 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Loading settings from /home2/surya_ravindra/.config/wandb/settings
2024-03-07 08:37:27,086 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Loading settings from /home2/surya_ravindra/CV_A2/wandb/settings
2024-03-07 08:37:27,087 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'CV_A1_Q2', 'entity': 'sriharib128', 'root_dir': '/home2/surya_ravindra/CV_A2', 'run_id': '7wvjejpc', 'sweep_param_path': '/home2/surya_ravindra/CV_A2/wandb/sweep-n67d31si/config-7wvjejpc.yaml', 'sweep_id': 'n67d31si'}
2024-03-07 08:37:27,087 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-07 08:37:27,087 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-07 08:37:27,087 INFO    MainThread:3776 [wandb_init.py:_log_setup():526] Logging user logs to /home2/surya_ravindra/CV_A2/wandb/run-20240307_083727-7wvjejpc/logs/debug.log
2024-03-07 08:37:27,087 INFO    MainThread:3776 [wandb_init.py:_log_setup():527] Logging internal logs to /home2/surya_ravindra/CV_A2/wandb/run-20240307_083727-7wvjejpc/logs/debug-internal.log
2024-03-07 08:37:27,087 INFO    MainThread:3776 [wandb_init.py:init():566] calling init triggers
2024-03-07 08:37:27,088 INFO    MainThread:3776 [wandb_init.py:init():573] wandb.init called with sweep_config: {'batch_size': 8, 'epochs': 5, 'learning_rate': 0.001, 'optimizer': 'sgd'}
config: {}
2024-03-07 08:37:27,088 INFO    MainThread:3776 [wandb_init.py:init():616] starting backend
2024-03-07 08:37:27,088 INFO    MainThread:3776 [wandb_init.py:init():620] setting up manager
2024-03-07 08:37:27,256 ERROR   MainThread:3776 [wandb_init.py:init():1204] error
Traceback (most recent call last):
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1176, in init
    run = wi.init()
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 621, in init
    manager._inform_init(
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/wandb_manager.py", line 200, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/service/service_sock.py", line 39, in _svc_inform_init
    self._sock_client.send(inform_init=inform_init)
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2024-03-07 08:38:27,637 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Current SDK version is 0.16.4
2024-03-07 08:38:27,638 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Configure stats pid to 3776
2024-03-07 08:38:27,638 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Loading settings from /home2/surya_ravindra/.config/wandb/settings
2024-03-07 08:38:27,638 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Loading settings from /home2/surya_ravindra/CV_A2/wandb/settings
2024-03-07 08:38:27,638 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'CV_A1_Q2', 'entity': 'sriharib128', 'root_dir': '/home2/surya_ravindra/CV_A2', 'run_id': '7wvjejpc', 'sweep_param_path': '/home2/surya_ravindra/CV_A2/wandb/sweep-n67d31si/config-7wvjejpc.yaml', 'sweep_id': 'n67d31si'}
2024-03-07 08:38:27,638 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-07 08:38:27,639 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-07 08:38:27,639 INFO    MainThread:3776 [wandb_init.py:_log_setup():526] Logging user logs to /home2/surya_ravindra/CV_A2/wandb/run-20240307_083827-7wvjejpc/logs/debug.log
2024-03-07 08:38:27,639 INFO    MainThread:3776 [wandb_init.py:_log_setup():527] Logging internal logs to /home2/surya_ravindra/CV_A2/wandb/run-20240307_083827-7wvjejpc/logs/debug-internal.log
2024-03-07 08:38:27,639 INFO    MainThread:3776 [wandb_init.py:init():566] calling init triggers
2024-03-07 08:38:27,639 INFO    MainThread:3776 [wandb_init.py:init():573] wandb.init called with sweep_config: {'batch_size': 8, 'epochs': 5, 'learning_rate': 0.001, 'optimizer': 'sgd'}
config: {}
2024-03-07 08:38:27,640 INFO    MainThread:3776 [wandb_init.py:init():616] starting backend
2024-03-07 08:38:27,640 INFO    MainThread:3776 [wandb_init.py:init():620] setting up manager
2024-03-07 08:38:27,807 ERROR   MainThread:3776 [wandb_init.py:init():1204] error
Traceback (most recent call last):
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1176, in init
    run = wi.init()
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 621, in init
    manager._inform_init(
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/wandb_manager.py", line 200, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/service/service_sock.py", line 39, in _svc_inform_init
    self._sock_client.send(inform_init=inform_init)
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2024-03-07 08:45:53,629 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Current SDK version is 0.16.4
2024-03-07 08:45:53,630 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Configure stats pid to 3776
2024-03-07 08:45:53,630 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Loading settings from /home2/surya_ravindra/.config/wandb/settings
2024-03-07 08:45:53,630 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Loading settings from /home2/surya_ravindra/CV_A2/wandb/settings
2024-03-07 08:45:53,630 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'CV_A1_Q2', 'entity': 'sriharib128', 'root_dir': '/home2/surya_ravindra/CV_A2', 'run_id': '7wvjejpc', 'sweep_param_path': '/home2/surya_ravindra/CV_A2/wandb/sweep-n67d31si/config-7wvjejpc.yaml', 'sweep_id': 'n67d31si'}
2024-03-07 08:45:53,630 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-07 08:45:53,630 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-07 08:45:53,631 INFO    MainThread:3776 [wandb_init.py:_log_setup():526] Logging user logs to /home2/surya_ravindra/CV_A2/wandb/run-20240307_084553-7wvjejpc/logs/debug.log
2024-03-07 08:45:53,631 INFO    MainThread:3776 [wandb_init.py:_log_setup():527] Logging internal logs to /home2/surya_ravindra/CV_A2/wandb/run-20240307_084553-7wvjejpc/logs/debug-internal.log
2024-03-07 08:45:53,631 INFO    MainThread:3776 [wandb_init.py:init():566] calling init triggers
2024-03-07 08:45:53,631 INFO    MainThread:3776 [wandb_init.py:init():573] wandb.init called with sweep_config: {'batch_size': 8, 'epochs': 5, 'learning_rate': 0.001, 'optimizer': 'sgd'}
config: {}
2024-03-07 08:45:53,631 INFO    MainThread:3776 [wandb_init.py:init():616] starting backend
2024-03-07 08:45:53,631 INFO    MainThread:3776 [wandb_init.py:init():620] setting up manager
2024-03-07 08:45:53,792 ERROR   MainThread:3776 [wandb_init.py:init():1204] error
Traceback (most recent call last):
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1176, in init
    run = wi.init()
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 621, in init
    manager._inform_init(
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/wandb_manager.py", line 200, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/service/service_sock.py", line 39, in _svc_inform_init
    self._sock_client.send(inform_init=inform_init)
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2024-03-07 08:51:11,196 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Current SDK version is 0.16.4
2024-03-07 08:51:11,198 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Configure stats pid to 3776
2024-03-07 08:51:11,198 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Loading settings from /home2/surya_ravindra/.config/wandb/settings
2024-03-07 08:51:11,199 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Loading settings from /home2/surya_ravindra/CV_A2/wandb/settings
2024-03-07 08:51:11,199 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'CV_A1_Q2', 'entity': 'sriharib128', 'root_dir': '/home2/surya_ravindra/CV_A2', 'run_id': '7wvjejpc', 'sweep_param_path': '/home2/surya_ravindra/CV_A2/wandb/sweep-n67d31si/config-7wvjejpc.yaml', 'sweep_id': 'n67d31si'}
2024-03-07 08:51:11,199 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-07 08:51:11,199 INFO    MainThread:3776 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-07 08:51:11,199 INFO    MainThread:3776 [wandb_init.py:_log_setup():526] Logging user logs to /home2/surya_ravindra/CV_A2/wandb/run-20240307_085111-7wvjejpc/logs/debug.log
2024-03-07 08:51:11,200 INFO    MainThread:3776 [wandb_init.py:_log_setup():527] Logging internal logs to /home2/surya_ravindra/CV_A2/wandb/run-20240307_085111-7wvjejpc/logs/debug-internal.log
2024-03-07 08:51:11,200 INFO    MainThread:3776 [wandb_init.py:init():566] calling init triggers
2024-03-07 08:51:11,200 INFO    MainThread:3776 [wandb_init.py:init():573] wandb.init called with sweep_config: {'batch_size': 8, 'epochs': 5, 'learning_rate': 0.001, 'optimizer': 'sgd'}
config: {}
2024-03-07 08:51:11,200 INFO    MainThread:3776 [wandb_init.py:init():616] starting backend
2024-03-07 08:51:11,201 INFO    MainThread:3776 [wandb_init.py:init():620] setting up manager
2024-03-07 08:51:11,387 ERROR   MainThread:3776 [wandb_init.py:init():1204] error
Traceback (most recent call last):
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1176, in init
    run = wi.init()
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 621, in init
    manager._inform_init(
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/wandb_manager.py", line 200, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/service/service_sock.py", line 39, in _svc_inform_init
    self._sock_client.send(inform_init=inform_init)
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home2/surya_ravindra/miniconda3/envs/pytorch_conda/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
